plugins {
    id "com.android.application"
}

def keystorePropertiesFile = rootProject.file("keystore.properties")
def keystoreProperties = new Properties()
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

android {
    namespace "com.anps.busdriver"
    compileSdk 35

    defaultConfig {
        applicationId "com.anps.busdriver"
        minSdk 23
        targetSdk 35
        versionCode 2
        versionName "1.0.1"

        buildConfigField "String", "APP_URL", "\"https://anpsbus.thebrainerp.com/driver-gps\""
    }

    signingConfigs {
        release {
            if (keystorePropertiesFile.exists()) {
                storeFile file(keystoreProperties["storeFile"])
                storePassword keystoreProperties["storePassword"]
                keyAlias keystoreProperties["keyAlias"]
                keyPassword keystoreProperties["keyPassword"]
            }
        }
    }

    buildTypes {
        release {
            if (keystorePropertiesFile.exists()) {
                signingConfig signingConfigs.release
            }
            minifyEnabled false
        }
    }

    buildFeatures {
        buildConfig true
    }
}
